// Sample rooms data with 20 rooms, some with all beds full, and others with varying availability
export const rooms = [
    { id: 1, name: "Room 1", beds: [{ id: 1, isAvailable: true }, { id: 2, isAvailable: true }, { id: 3, isAvailable: true }, { id: 4, isAvailable: true }, { id: 5, isAvailable: true }, { id: 6, isAvailable: true }, { id: 7, isAvailable: true }, { id: 8, isAvailable: true }, { id: 9, isAvailable: true }, { id: 10, isAvailable: true }, { id: 11, isAvailable: true }, { id: 12, isAvailable: true }, { id: 13, isAvailable: true }, { id: 14, isAvailable: true }, { id: 15, isAvailable: true }, { id: 16, isAvailable: true }, { id: 17, isAvailable: true }, { id: 18, isAvailable: true }, { id: 19, isAvailable: true }, { id: 20, isAvailable: true }] },
    { id: 2, name: "Room 2", beds: [{ id: 1, isAvailable: false }, { id: 2, isAvailable: false }, { id: 3, isAvailable: false }, { id: 4, isAvailable: false }, { id: 5, isAvailable: false }, { id: 6, isAvailable: false }, { id: 7, isAvailable: false }, { id: 8, isAvailable: false }, { id: 9, isAvailable: false }, { id: 10, isAvailable: false }, { id: 11, isAvailable: false }, { id: 12, isAvailable: false }, { id: 13, isAvailable: false }, { id: 14, isAvailable: false }, { id: 15, isAvailable: false }, { id: 16, isAvailable: false }, { id: 17, isAvailable: false }, { id: 18, isAvailable: false }, { id: 19, isAvailable: false }, { id: 20, isAvailable: false }] },
    { id: 3, name: "Room 3", beds: [{ id: 1, isAvailable: true }, { id: 2, isAvailable: false }, { id: 3, isAvailable: true }, { id: 4, isAvailable: false }, { id: 5, isAvailable: true }, { id: 6, isAvailable: false }, { id: 7, isAvailable: true }, { id: 8, isAvailable: false }, { id: 9, isAvailable: true }, { id: 10, isAvailable: false }, { id: 11, isAvailable: true }, { id: 12, isAvailable: false }, { id: 13, isAvailable: true }, { id: 14, isAvailable: false }, { id: 15, isAvailable: true }, { id: 16, isAvailable: false }, { id: 17, isAvailable: true }, { id: 18, isAvailable: false }, { id: 19, isAvailable: true }, { id: 20, isAvailable: false }] },
    { id: 4, name: "Room 4", beds: [{ id: 1, isAvailable: false }, { id: 2, isAvailable: false }, { id: 3, isAvailable: false }, { id: 4, isAvailable: false }, { id: 5, isAvailable: false }, { id: 6, isAvailable: false }, { id: 7, isAvailable: false }, { id: 8, isAvailable: false }, { id: 9, isAvailable: false }, { id: 10, isAvailable: false }, { id: 11, isAvailable: false }, { id: 12, isAvailable: false }, { id: 13, isAvailable: false }, { id: 14, isAvailable: false }, { id: 15, isAvailable: false }, { id: 16, isAvailable: false }, { id: 17, isAvailable: false }, { id: 18, isAvailable: false }, { id: 19, isAvailable: false }, { id: 20, isAvailable: false }] },
    { id: 5, name: "Room 5", beds: [{ id: 1, isAvailable: true }, { id: 2, isAvailable: true }, { id: 3, isAvailable: false }, { id: 4, isAvailable: false }, { id: 5, isAvailable: true }, { id: 6, isAvailable: false }, { id: 7, isAvailable: true }, { id: 8, isAvailable: false }, { id: 9, isAvailable: true }, { id: 10, isAvailable: false }, { id: 11, isAvailable: true }, { id: 12, isAvailable: false }, { id: 13, isAvailable: true }, { id: 14, isAvailable: false }, { id: 15, isAvailable: true }, { id: 16, isAvailable: false }, { id: 17, isAvailable: true }, { id: 18, isAvailable: false }, { id: 19, isAvailable: true }, { id: 20, isAvailable: false }] },



  ]
  